### ISSUE TITLE
`runpath` may not take effect in 'sub-library'

### ISSUE THREAD

**Issue by Crazyokd** [haampie/libtree#93]
![image](https://github.com/haampie/libtree/assets/74645100/53280a90-98d8-494d-aedf-d10df6f104de)

**Comment by haampie** [comment]
The dynamic loader traverses the dependency graph in breadth-first order and caches nodes by soname. `libtree` does not cache by soname, which is useful to expose problems.

The `not found` issues you see are likely legitimate issues with the libraries that need `libogscore.so.2`: their dependent is missing an rpath, or you meant to use `rpath` (inherited) instead of `runpath` (not inherited).
